version: '3.8'

# Default environment variables
x-env: &default-environment
  NODE_ENV: development
  PORT: 3000
  MONGO_URI: mongodb://mongo:27017/curvvtech
  JWT_ACCESS_SECRET: your_jwt_access_secret
  JWT_REFRESH_SECRET: your_jwt_refresh_secret
  JWT_ACCESS_TTL: 15m
  JWT_REFRESH_TTL: 7d
  RATE_LIMIT_MAX: 100
  RATE_LIMIT_WINDOW_MS: 60000

services:
  app:
    build:
      context: .
      target: production
      args:
        - NODE_ENV=production
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      <<: *default-environment
      # Override any variables from .env file
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:${PORT:-3000}/health', (res) => { if (res.statusCode !== 200) throw new Error() }).on('error', () => { process.exit(1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "'db.runCommand({ ping: 1 }).ok'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-password}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-curvvtech}

  # MongoDB Express for admin UI (optional)
  mongo-express:
    image: mongo-express:1.0
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME:-admin}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-password}
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

volumes:
  mongo-data:
    name: curvvtech-mongo-data
